version: '3.7'
services:
  productapp:
    build: ./docker/php
    volumes:
      - ./:/var/www

  productapp-nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
    depends_on:
      - productapp